CREATE TABLE dogs
(
    id       BIGINT generated by default as identity primary key,
    name     TEXT    NOT NULL,
    breed    TEXT    NOT NULL,
    age      INTEGER NOT NULL,
    suit     TEXT    NOT NULL,
    gender   TEXT    NOT NULL,
    owner_id BIGINT  NOT NULL
);

CREATE TABLE cats
(
    id       BIGINT generated by default as identity primary key,
    name     TEXT    NOT NULL,
    breed    TEXT    NOT NULL,
    age      INTEGER NOT NULL,
    suit     TEXT    NOT NULL,
    gender   TEXT    NOT NULL,
    owner_id BIGINT  NOT NULL
);

CREATE TABLE reports
(
    id     BIGINT generated by default as identity primary key,
    date   timestamp NOT NULL,
    photo  bytea     NOT NULL,
    report TEXT      NOT NULL
);

CREATE TABLE clients
(
    id         BIGINT generated by default as identity primary key,
    name       TEXT    NOT NULL,
    passport   TEXT    NOT NULL,
    shelter_id INTEGER NOT NULL
);

CREATE TABLE cat_owners
(
    owner_id BIGINT generated by default as identity primary key,
    name     TEXT NOT NULL,
    passport TEXT NOT NULL,
    pets     cats NOT NULL
);

CREATE TABLE dog_owners
(
    owner_id BIGINT generated by default as identity primary key,
    name     TEXT NOT NULL,
    passport TEXT NOT NULL,
    pets     dogs NOT NULL
);