CREATE TABLE dogs
(
    id     BIGINT generated by default as identity primary key,
    name   TEXT    NOT NULL,
    breed  TEXT    NOT NULL,
    age    INTEGER NOT NULL,
    suit   TEXT    NOT NULL,
    gender TEXT    NOT NULL
);

CREATE TABLE cats
(
    id     BIGINT generated by default as identity primary key,
    name   TEXT    NOT NULL,
    breed  TEXT    NOT NULL,
    age    INTEGER NOT NULL,
    suit   TEXT    NOT NULL,
    gender TEXT    NOT NULL
);